ALTER TABLE "GeofencePolicy"
ADD COLUMN IF NOT EXISTS "arrivalGraceMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS "autoMissedGraceMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN IF NOT EXISTS "requireGateTapForOpen" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "allowPicketOverride" BOOLEAN NOT NULL DEFAULT true;
