ALTER TYPE "PrayerType" ADD VALUE IF NOT EXISTS 'ASHAR';
ALTER TYPE "ReconciliationFlagType" ADD VALUE IF NOT EXISTS 'BELUM_SCAN_ASHAR';

ALTER TABLE "AttendancePolicy"
  ADD COLUMN IF NOT EXISTS "requireStudentAsharForAfternoon" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "asharStartTime" TEXT NOT NULL DEFAULT '15:00',
  ADD COLUMN IF NOT EXISTS "asharEndTime" TEXT NOT NULL DEFAULT '16:30',
  ADD COLUMN IF NOT EXISTS "asharRequiredClassEndTime" TEXT NOT NULL DEFAULT '15:00',
  ADD COLUMN IF NOT EXISTS "allowStudentAsharCheckoutOverride" BOOLEAN NOT NULL DEFAULT true;
