export const uiCopy = {
  appName: 'SchoolHub e-Hadir',
  schoolName: 'MAN 1 Rokan Hulu',
  nav: {
    studentDashboard: 'Beranda Siswa',
    studentCheckIn: 'Absen Masuk Siswa',
    teacherDashboard: 'Beranda Guru',
    teacherAttendance: 'Isi Presensi',
    teacherCorrection: 'Perbaikan Presensi',
    teacherRecap: 'Ringkasan Kelas',
    teacherMyAttendance: 'Kehadiran Saya',
    adminDashboard: 'Beranda Admin',
    adminAnomaly: 'Pusat Anomali',
    adminLiveMonitor: 'Pemantauan Langsung',
    adminHistory: 'Riwayat Presensi',
    adminSchedule: 'Jadwal dan Sesi',
    adminSmartCard: 'Kartu Pintar',
    adminMasterData: 'Data Utama',
    adminReports: 'Laporan',
    adminAudit: 'Jejak Audit',
    adminSettings: 'Pengaturan',
    profile: 'Profil'
  },
  topbar: {
    openMenu: 'Buka menu navigasi',
    quickAccess: 'Akses Cepat',
    account: 'Akun',
    profile: 'Profil',
    logout: 'Keluar',
    uiPanel: 'Tata Tampilan'
  },
  tweak: {
    title: 'Tata Tampilan',
    description: 'Atur kerapatan, sudut, gerak, dan nuansa warna tampilan sesuai kebutuhan Anda.',
    density: 'Kerapatan',
    densityComfortable: 'Nyaman',
    densityCompact: 'Ringkas',
    radius: 'Bentuk Sudut',
    radiusSoft: 'Membulat',
    radiusSharp: 'Tegas',
    motion: 'Gerak Antarmuka',
    motionCalm: 'Tenang',
    motionBalanced: 'Seimbang',
    motionVivid: 'Dinamis',
    emphasis: 'Fokus Tampilan',
    emphasisData: 'Fokus Data',
    emphasisContext: 'Fokus Konteks',
    palette: 'Nuansa Warna',
    paletteEmerald: 'Hijau',
    paletteSlate: 'Biru Abu',
    paletteSunset: 'Senja',
    reset: 'Kembalikan Standar'
  }
} as const;
